spring.datasource.url=jdbc:postgresql://localhost:5432/teste_bd
spring.datasource.username=postgres
spring.datasource.password=Elefantamon1.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra as queries SQL no console
spring.jpa.show-sql=true

# Atualiza??o do schema (cria tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=create-drop