spring.datasource.url=jdbc:postgresql://(link do BD):5432/postgres
spring.datasource.username=(Usuario do BD)
spring.datasource.password=(Senha do BD)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra as queries SQL no console
spring.jpa.show-sql=true

# Atualiza??o do schema (cria tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=create-drop